# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='middlename',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
    ]
