# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20161110_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='middlename',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
