# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 04:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('profiles', '0004_auto_20161111_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('middlename', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
