# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_userprofile_phone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_code',
            field=models.CharField(choices=[('IN', 'in'), ('US', 'us')], max_length=2),
        ),
    ]
