# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 11:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20161111_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits number.', regex='^\\d{10}$')]),
        ),
    ]
