# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20161111_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_code',
            field=models.CharField(blank=True, choices=[('IN', 'India(+91)'), ('US', 'USA(+1)')], max_length=2),
        ),
    ]
