# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20161114_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='street1',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
