# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20161115_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_code',
            field=models.CharField(blank=True, choices=[('+91', 'India(+91)'), ('+1', 'USA(+1)')], max_length=3),
        ),
    ]
