# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 04:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20161115_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=8, validators=[django.core.validators.RegexValidator(message='PINCODE must be 8 digits number.', regex='^\\d{8}$')]),
        ),
    ]
