# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 04:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_userprofile_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=6, validators=[django.core.validators.RegexValidator(message='PINCODE must be 6 digits number.', regex='^\\d{6}$')]),
        ),
    ]
