# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 08:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20161115_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits number.', regex='^\\d{10}$')]),
        ),
    ]
